baseURL = "https://glngn.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "The Goal Engine Server"
theme = "cayman-hugo-theme"

# Google analytics
googleAnalytics = "UA-4000376-5"

# Disqus comments
disqusShortname = "yourdiscussshortname"

# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/blog/:filename/"

[params]
  # Header text, can be markdown
  project_name = "The Goal Engine Server (glngn)"
  project_tagline = "Turn your business into software."

  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  # Footer text, can be markdown
  footer = "Copyright &copy; <a href=\"https://dogheadbone.com\">Dogheadbone, LLC</a>"

  # If true, the CSS/JS for Katex math typesetting are enabled
  katex = true

  # Breakpoints
  large_breakpoint = "64em"
  medium_breakpoint = "42em"

  # Header colors
  header_heading_color = "#fff"
  header_background_color = "#283048"
  header_background_color_secondary = "#859398"

  # Text colors
  section_headings_color = "#de3423"
  body_text_color = "#606c71"
  body_link_color = "#380d09"
  blockquote_text_color = "#819198"

  # Code colors
  code_background_color = "#f3f6fa"
  code_text_color = "#567482"

  # Border colors
  border_color = "#5c150e"
  table_border_color = "#e9ebec"
  hr_border_color = "#eff0f1"

[menu]
  [[menu.nav]]
    name = "Install"
    url = "/"
    weight = 2
  [[menu.nav]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.nav]]
    name = "Support"
    url = "/support/"
    weight = 4
  [[menu.nav]]
    name = "Documentation"
    url = "http://docs.glngn.com"
    weight = 5
